name: 'Documentation'

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Doxygen Action C++
        uses: mattnotmitt/doxygen-action@v1.3.1
        with:
          working-directory: '.'
          doxyfile-path: 'doc/Doxyfile'
      - name: Upload Output Directory
        uses: actions/upload-artifact@v2
        with:
          name: doc-files
          path: doc
          retention-days: 1

  copy:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Download Output Directory
        uses: actions/download-artifact@v2
        with:
          name: doc-files
          path: docDir

      - run: ls -l
      - run: cp -R ./docDir/html/* .

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author name: Vishnenko Maxim
          author email: vishnenko.maxim"gmail.com
          message: 'Update docs'
          branch: gh-pages
          add: '["./*"]'
